#!/bin/bash
# Copyright (c) 2017 Square Panda Inc.
# All Rights Reserved.
# Dissemination, use, or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from Square Panda Inc.
# @Last modified by:   Gaurang Pansare

echo "Starting initialization"

# Node js is required
node_check=$(command -v node)
if [[ -z "${node_check}" || !($(node --version) == v10*) ]]; then
  echo "Intalling node v10"

  # Fetch official setup script
  curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  if [[ "$?" != "0" ]]; then
    echo "ERROR: Failed to get setup script for required package node js."
    exit 1
  fi

  # Go get and install packages
  sudo apt-get install -y nodejs
  if [[ "$?" != "0" ]]; then
    echo "ERROR: Failed to install required package node js."
    exit 2
  fi
else
  echo "Node v10 already installed"
fi

sudo apt update
sudo apt install redis-server
sudo npm install -g redis-commander

echo "Completed initialzation"
