#!/bin/bash
# Copyright (c) 2017 Square Panda Inc.
# All Rights Reserved.
# Dissemination, use, or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from Square Panda Inc.
# @Last modified by:   arjun

is_running=$(./node_modules/.bin/forever list | grep "redisBull")
if [[ "$?" == "1" ]]; then
  echo "Service is not running"
  exit
else
  echo "Attempting stop of:"
  echo "${is_running}"
fi

npm stop
exit $?
