#!/bin/bash
# Copyright (c) 2017 Square Panda Inc.
# All Rights Reserved.
# Dissemination, use, or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from Square Panda Inc.
# @Last modified by:   arjun

sp_environment=$1
if [[ -z "${sp_environment}" ]]; then
  sp_environment='local'
fi

export SP_ENVIRONMENT=${sp_environment}

npm start
exit $?
